import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Pizza } from "lucide-react";
import { NavLink } from "@/components/Header/Container/ActionContainer/NavLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <Header.RootContainer>
          <Header.LogoContainer.Logo>
            <Pizza size={24} />
          </Header.LogoContainer.Logo>
          <Header.ActionContainer>
            <NavLink title="RESERVA" url="#" />
            <NavLink title="CARDÁPIO" url="#" />
            <NavLink title="CONTATO" url="#" />
          </Header.ActionContainer>
        </Header.RootContainer>
        {children}
      </body>
    </html>
  );
}
